// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6-n-b80PvVkATZ9G63nBtN6UCduDShhw',
    appId: '1:294076438137:web:487e56317b3597443766a8',
    messagingSenderId: '294076438137',
    projectId: 'adapted-app',
    authDomain: 'adapted-app.firebaseapp.com',
    storageBucket: 'adapted-app.firebasestorage.app',
    measurementId: 'G-K3YKVCNZY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8XN-nFpMbg24n8TB09LAER4kSq1Mjn4I',
    appId: '1:294076438137:android:4b7965e545b9f4b03766a8',
    messagingSenderId: '294076438137',
    projectId: 'adapted-app',
    storageBucket: 'adapted-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSHJGCPueHA0k9kpQbWbZrWgj--mg5JQw',
    appId: '1:294076438137:ios:53e973a50504f2f03766a8',
    messagingSenderId: '294076438137',
    projectId: 'adapted-app',
    storageBucket: 'adapted-app.firebasestorage.app',
    iosBundleId: 'com.adapted.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSHJGCPueHA0k9kpQbWbZrWgj--mg5JQw',
    appId: '1:294076438137:ios:bc5495c0b306d2093766a8',
    messagingSenderId: '294076438137',
    projectId: 'adapted-app',
    storageBucket: 'adapted-app.firebasestorage.app',
    iosBundleId: 'com.adapted.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6-n-b80PvVkATZ9G63nBtN6UCduDShhw',
    appId: '1:294076438137:web:a2868d21b08e97133766a8',
    messagingSenderId: '294076438137',
    projectId: 'adapted-app',
    authDomain: 'adapted-app.firebaseapp.com',
    storageBucket: 'adapted-app.firebasestorage.app',
    measurementId: 'G-P53WGFFWSZ',
  );
}